# Generated by Django 4.2.15 on 2024-09-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financesapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SignIn",
            new_name="Users",
        ),
        migrations.DeleteModel(
            name="SignUp",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="login",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="passwd",
            new_name="username",
        ),
    ]
