# Generated by Django 4.2.15 on 2024-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financesapp", "0002_rename_signin_users_delete_signup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "title",
                    models.CharField(
                        max_length=30, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("author", models.CharField(max_length=30)),
                ("text", models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name="Users",
            new_name="Form",
        ),
    ]
