# Generated by Django 4.2.15 on 2024-09-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financesapp", "0003_posts_rename_users_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="auto_increment_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="posts",
            name="title",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
