# Generated by Django 4.2.15 on 2024-09-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financesapp", "0004_posts_auto_increment_id_alter_posts_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="auto_increment_id",
        ),
        migrations.AddField(
            model_name="posts",
            name="id_p",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
