# Generated by Django 4.2.15 on 2024-09-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financesapp", "0005_remove_posts_auto_increment_id_posts_id_p"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="text",
            field=models.CharField(max_length=150),
        ),
    ]
