# Generated by Django 4.2.15 on 2024-09-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financesapp", "0007_alter_posts_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="text",
            field=models.CharField(max_length=900),
        ),
    ]
